logging:
    level:
        ROOT: DEBUG
        com.jageton.server: DEBUG

spring:
    profiles:
        active: dev
        include:
            - swagger
    devtools:
        restart:
            enabled: true
            additional-exclude: .h2.server.properties
        livereload:
            enabled: false
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./target/h2db/db/hipster;DB_CLOSE_DELAY=-1
        username: chat
        password:
        hikari:
            poolName: Hikari
            auto-commit: false
    h2:
        console:
            enabled: false
    jpa:
        database-platform: io.github.jhipster.domain.util.FixedH2Dialect
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
            hibernate.cache.hazelcast.instance_name: hipster
            hibernate.cache.use_minimal_puts: true
            hibernate.cache.hazelcast.use_lite_member: true
    messages:
        cache-duration: PT1S
    thymeleaf:
        cache: false

server:
    port: 8080

# application:
